### ISSUE TITLE
Create a reusable modal to replace all alerts and default dialog windows

### ISSUE THREAD

**Issue by alexandra-lim** [the-collab-lab/tcl-12-smart-shopping-list#39]
Create a reusable modal to replace all instances of window alerts and other default dialog windows. 

Base the new modal off of the Delete Modal component, and refactor Delete Modal component to use the new modal template.

Also make new modal accessible - to discuss with EJ

**Comment by stacietaylorcima** [comment]
Try to find a good library with an accessible modal and EJ will host a small workshop that discusses the success criteria for a proper modal!
