### ISSUE TITLE
Restructure Database

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-12-smart-shopping-list#42]
**User story:** As a developer, I would like a database that will scale more fluidly as we add new features. 

**Acceptance criteria:** 
* All API requests (getting, updating, deleting) work as before
* Filtering the list works as before
* Ordering the list works as before

**Pain points with current implementations:** 
* Too much nesting: We currently have to dig in three layers to get to an item's details. 
* Querying is complex and doesn't use the methods that firestore recommends. 
* Firebase docs scare us away from nesting, BUT it can be useful. We currently have objects with properties but we can do something else to make it easier to add and access those elements. All lists are not evil. 

**Resources:** 
* [Advice on how to structure data from Firestore's docs](https://firebase.google.com/docs/firestore/manage-data/structure-data)
* Search what other folks are doing. 

**Notes:** 
* Suggestion: All lists are not evil, we could consider using a proper list here. 
* Talk openly. Share openly about your ideas in Slack. Ask for thoughts! 
* Firestore allows nested collections. Collection of lists with a subcollection that is the items of the list.

**Comment by mxmason** [comment]
@edenbekele, @alexandra-lim: Don't forget to make sure that an empty list renders the prompt we expect! It should tell the user there are no items and prompt them to make their first one!
