### ISSUE TITLE
Aria label for details button not rendering properly

### ISSUE THREAD

**Issue by alexandra-lim** [the-collab-lab/tcl-12-smart-shopping-list#52]
On list view, the Details button's aria label is rendering incorrectly. The aria label should read "Details for `item name`" as opposed to "`[Object object]`"

![Screen Shot 2020-11-29 at 5 19 37 PM](https://user-images.githubusercontent.com/49457972/100555047-19c08600-3267-11eb-9aa9-40ad4460008b.png)

**Comment by GabbyJ** [comment]
needed to change item to item.name on the aria-label
